import time

print("123 + 12")
print((123 + 12) * 10)
print("------------------------------------------------------------------------")
print("Octal:", 0o123)
print("Hexadecimal:", 0x123)
print("Binário:", 0b10)
print("------------------------------------------------------------------------")
#Convertendo para binário
print("Binário:", bin(42))
#Convertendo para octal
print("Octal:", oct(42))
#Convertendo para hexadecimal
print("Hexadecimal:", hex(42))
print("------------------------------------------------------------------------")
print("Floats:")
print(0.4)
print(4.0)
print(4)
print(4.0 + 4)
print("------------------------------------------------------------------------")
print(4.)
print(.4)
print("------------------------------------------------------------------------")
print(3e8)
#6,62607 x 10(-34)
print(6.62607e-34)
#Representação do número 0.0000000000000000000001
print(0.0000000000000000000001)
print(1e-22)
print("------------------------------------------------------------------------")
print("Strings:")
print('Brasil "1 x 0" Inglaterra')
print("------------------------------------------------------------------------")
print("Boolean ou Bool")
print("------------------------------------------------------------------------")
print(True)
print(False)
print("Comparação 1:",True > False)
print("Comparação 2:",False > True)

print("------------------------------------------------------------------------")
time.sleep(2)